# This workflow will deploy a JAR artifact along with the regular build.

name: GitHub Packages Deployment
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload to GitHub Packages with Gradle
        env:
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          OSSRH_USERNAME: Stinggyray
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          VERSION: ${{ github.ref }}
        run: ./gradlew publish
